<html>
<head>
<style type="text/css">
<!--
a:link{color:red;}
a:alink{color:blue;}
a:vlink{color:black;}
-->
</style>
<script language="javascript" src="f:\9908\01\sam\javascript.js">


</script>

</head>
<body bgcolor="#b5f9b5" onload="moveheart()">

<div style="position:absolute; top:80 ; left:350">
<img src="f:/9908/04/BRAIN.gif"  width="570" height="450" border="0" usemap="#f:/9908/04/BRAIN.gif"></div>
<h1 id=h1head style="position:absolute;color:red;top:20;left:200;font-family:ravie;filter:glow(color=#fa99cc,strength=10);align:center;z-index:1" onmouseover="hover()" onmouseout="hoveroff()">CONTESTS</H1>


<img id=divheart1 Style="Position:Absolute; Top:420; Left:480; z-index:-1; Width:120; Height:120; Align:center" src="f:/9908/04/newheart.gif" width="100%" height="100%" border="0">

<img id=divheart2 Style="Position:Absolute; Top:520; Left:00; z-index:-1; Width:120; Height:120; Align:center" src="f:/9908/04/newheart.gif" width="100%" height="100%" border="0">				

<img id=divheart3 Style="Position:Absolute; Top:200; Left:390; z-index:-1; Width:120; Height:120; Align:center" src="f:/9908/04/newheart.gif" width="100%" height="100%" border="0">


<div id="nav" style="font-family:papyrus;filter:shadow(color=#a9f1b4);position:absolute;top:50;left:20;width:200"><br><br><br><a href="IQTest">IQ Test</a><br><br><a href="gamble">Gambling</a><br><br><a href="film">FilmiChakkar</a><br><br><a href="#message">Message</a><br><br><h1><a href="Flame.html">Flame</a></h1>
</div>
<div id="marque" style="position:absolute;top:335;left:110"><h1><marquee style="font-family:wingdings;" behavior="alternate" scrolldelay="100" width="75">E</marquee></h1></div>

<map name="f:/9908/04/BRAIN.gif">
<area shape="rect" coords="45,10,96,61" title="mix.html" href="mix.html">
<area shape="rect" coords="45,61,96,112" title="veg1.html" href="veg1.html">
<area shape="rect" coords="96,10,156,61"  title="message contest" href="#message ">
<area shape="rect" coords="96,61,156,112" title="wonder.html" href="wonder.html">
<area shape="rect" coords="156,112,207,163" title="xyz.html" href="xyz.html">
</map>

<div id="message" style="position:absolute;top:400;left:100">
<table bgcolor= "#cfffcf" BORDER="1"><tr><td>
Write message for your dear one and watch it get displayed on our site...!!</font><br><br>
Message &nbsp&nbsp<textarea rows="4" cols="15"></textarea>
from&nbsp&nbsp
<input type="text" value="">
<br>
<center><input type="button" value="submit"></center></td></tr></table>
</div>

<div id="flameblock" style="position:absolute;top:600;left:100">
<form>
<input type="text" name="name1" value=""><br><br>
<input type="text" name="name2" value="">
<br><br><br>

<div style=position:absolute;top:650;left:170;">
<input type="button" name="but" value="flame" onclick="flame()">&nbsp<input type="button" name="reset" value="Reset" onclick="set()"></div>

<div style=position:absolute;top:10;left:220;"><textarea name="name3" rows="4" cols="30" value=""></textarea></div>

</form>
</div>
</body>
</html>

